/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Book;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BooksWebServiceApi
 */
@Ignore
public class BooksWebServiceApiTest {

    private final BooksWebServiceApi api = new BooksWebServiceApi();

    
    /**
     * deleteBookByIsbn
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBookByIsbnUsingDELETETest() throws ApiException {
        String isbn = null;
        api.deleteBookByIsbnUsingDELETE(isbn);

        // TODO: test validations
    }
    
    /**
     * findBookByIsbn
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBookByIsbnUsingGETTest() throws ApiException {
        String isbn = null;
        Book response = api.findBookByIsbnUsingGET(isbn);

        // TODO: test validations
    }
    
    /**
     * newBook
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newBookUsingPOSTTest() throws ApiException {
        String title = null;
        Double price = null;
        String response = api.newBookUsingPOST(title, price);

        // TODO: test validations
    }
    
    /**
     * updateBook
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateBookUsingPUTTest() throws ApiException {
        String isbn = null;
        Book toUpdate = null;
        Book response = api.updateBookUsingPUT(isbn, toUpdate);

        // TODO: test validations
    }
    
}
