/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StoreWebServiceApi
 */
@Ignore
public class StoreWebServiceApiTest {

    private final StoreWebServiceApi api = new StoreWebServiceApi();

    
    /**
     * getStock
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockUsingGETTest() throws ApiException {
        String category = null;
        String item = null;
        String response = api.getStockUsingGET(category, item);

        // TODO: test validations
    }
    
    /**
     * setStock
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setStockUsingPOSTTest() throws ApiException {
        String category = null;
        String item = null;
        Integer stock = null;
        api.setStockUsingPOST(category, item, stock);

        // TODO: test validations
    }
    
}
