/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebIsbnGeneratorApi
 */
//@Ignore
public class WebIsbnGeneratorApiTest {

    private final WebIsbnGeneratorApi api = new WebIsbnGeneratorApi();

    
    /**
     * nextIsbn
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nextIsbnUsingPOSTTest() throws ApiException {
        String response = api.nextIsbnUsingPOST();
        System.out.println("RESPONSE: " + response);
        // TODO: test validations
    }
    
}
